{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cqrs-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.shopGatewayHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shop-gateway
                port:
                  number: 8080
    - host: {{ .Values.ingress.adminApiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shop-admin-api
                port:
                  number: 8080
    - host: {{ .Values.ingress.shopFrontendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shop
                port:
                  number: 3000
{{- end }}
