services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cqrs-demo-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:1.1.2
    container_name: cqrs-demo-servicebus
    depends_on:
      - sqledge
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./infrastructure/servicebus-emulator-config.json:/ServiceBus_Emulator/Config/Config.json

  sqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: cqrs-demo-sqledge
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"

volumes:
  sqlserver_data:
