#!/usr/bin/env bash
set -euo pipefail
export DOTNET_ROOT="${DOTNET_ROOT:-$HOME/.dotnet}"
export PATH="$DOTNET_ROOT:$PATH"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "Start infrastructure: docker compose -f infra/docker/docker-compose.yml up -d"
docker compose -f "$ROOT/infra/docker/docker-compose.yml" up -d
sleep 25

echo ""
echo "Run each in a separate terminal (or use tmux):"
echo ""
echo "# Workers (8)"
echo "dotnet run --project $ROOT/backend/src/Services/Reporting/Reporting.Projection.Worker"
echo "dotnet run --project $ROOT/backend/src/Services/User/User.Projection.Worker"
echo "dotnet run --project $ROOT/backend/src/Services/Product/Product.Projection.Worker"
echo "dotnet run --project $ROOT/backend/src/Services/Cart/Cart.Projection.Worker"
echo "dotnet run --project $ROOT/backend/src/Services/Order/Order.Projection.Worker"
echo "dotnet run --project $ROOT/backend/src/Services/Order/Order.Integration.Worker"
echo "dotnet run --project $ROOT/backend/src/Services/Payment/Payment.Projection.Worker"
echo "dotnet run --project $ROOT/backend/src/Services/Saga/CheckoutSaga.Worker"
echo ""
echo "# APIs (14)"
echo "dotnet run --project $ROOT/backend/src/Services/Reporting/Reporting.Queries.Api"
echo "dotnet run --project $ROOT/backend/src/Services/User/User.Commands.Api"
echo "dotnet run --project $ROOT/backend/src/Services/User/User.Queries.Api"
echo "dotnet run --project $ROOT/backend/src/Gateway/Shop.Admin.Api"
echo "dotnet run --project $ROOT/backend/src/Gateway/Shop.Gateway.Api"
echo ""
echo "# Admin portal"
echo "cd $ROOT/frontend/admin && pnpm install && pnpm dev"
echo ""
echo "dotnet run --project $ROOT/backend/src/Services/Saga/CheckoutSaga.Api"
echo "dotnet run --project $ROOT/backend/src/Services/Product/Product.Commands.Api"
echo "dotnet run --project $ROOT/backend/src/Services/Product/Product.Queries.Api"
echo "dotnet run --project $ROOT/backend/src/Services/Cart/Cart.Commands.Api"
echo "dotnet run --project $ROOT/backend/src/Services/Cart/Cart.Queries.Api"
echo "dotnet run --project $ROOT/backend/src/Services/Order/Order.Commands.Api"
echo "dotnet run --project $ROOT/backend/src/Services/Order/Order.Queries.Api"
echo "dotnet run --project $ROOT/backend/src/Services/Payment/Payment.Commands.Api"
echo "dotnet run --project $ROOT/backend/src/Services/Payment/Payment.Queries.Api"
